language: java
jdk:
  - oraclejdk8

env:
  # set NEXT_ROOT, so apps will start
  - NEXT_ROOT=/home/travis/build

script: "mvn verify"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
